import { RectangleGroupIcon } from "@heroicons/react/24/solid";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { StickyHeader } from "~/components/header";

export const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Goals | Finance Pro</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-[100vh] bg-zinc-900 text-white">
        <StickyHeader title="Goals" backButton />
        <div className="h-[5vh]" />
        <div className="grid min-h-[95vh] w-full items-center justify-center">
          <div className="bg-zinc-600 p-2 rounded">
            <Link href="/goals/sections/view">
              <div className="flex items-center justify-center gap-2 p-4 rounded-md">
                <RectangleGroupIcon className="w-8 h-8" />
                <p className="text-lg font-semibold">View Sections</p>
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Page;
