import { SignIn, useClerk } from "@clerk/nextjs";
import { type NextPage } from "next";
import { PencilSquareIcon } from "@heroicons/react/24/solid";
import Link from "next/link";
import Head from "next/head";

const Page: NextPage = () => {
  const { user } = useClerk();

  if (!user) {
    return (
      <div>
        <SignIn />
      </div>
    );
  }

  const id = user.id;

  return (
    <>
      <Head>
        <title>Overview | FinPlan</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-[100vh] bg-zinc-800 text-white">
        <div className="flex items-center justify-between border-b border-zinc-600 bg-zinc-700 p-2 font-semibold drop-shadow-md">
          <h1 className="text-2xl">Overview</h1>
          <div>
            <Link href="/new-item">
              <div className="rounded-full bg-blue-600 p-2 px-4 transition duration-200 hover:scale-105 hover:bg-blue-500">
                <PencilSquareIcon className="h-5 w-5" />
              </div>
            </Link>
          </div>
        </div>
        <div className="p-2">
          <h1 className="text-3xl font-semibold">Payables</h1>
        </div>
      </main>
    </>
  );
};

export default Page;
