import {
  SignInButton,
  SignOutButton,
  UserButton,
  useClerk,
} from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const { user } = useClerk();
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-[100vh] bg-zinc-800">
        {user && (
          <div className="flex h-10 justify-end p-2">
            <UserButton />
          </div>
        )}
        <div className="flex h-[90vh] w-full items-center justify-center">
          {user ? (
            <div>
              <Link href="/" className="rounded bg-blue-700 p-3 font-semibold text-white">
                View your Finances
              </Link>
            </div>
          ) : (
            <div>
              <SignInButton />
            </div>
          )}
        </div>
      </div>
    </>
  );
}
